---
# Configuration settings for sckg
defaults:
  generic:
    module: 'sckg.etl.generic'
    class: 'Generic'
  templates:
    cypher:
      path: 'data/templates/cypher/'
regimes:
  - name: '800_53'
    description: 'NIST 800-53'
    document:
      source: 'http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r4.pdf'
      parsable: 'data/regimes/nist_800-53r4.tsv'
    etl:
      module: 'sckg.etl.nist_800_53'
      class: 'NIST80053'
    meta:
      render_related: False
      families:
        AC: 'Access Control'
        MP: 'Media Protection'
        AT: 'Awareness and Training'
        PE: 'Physical and Environmental Protection'
        AU: 'Audit and Accountability'
        PL: 'Planning'
        CA: 'Security Assessment and Authorization'
        PS: 'Personnel Security'
        CM: 'Configuration Management'
        RA: 'Risk Assessment'
        CP: 'Contingency Planning'
        SA: 'System and Services Acquisition'
        IA: 'Identification and Authentication'
        SC: 'System and Communications Protection'
        IR: 'Incident Response'
        SI: 'System and Information Integrity'
        MA: 'Maintenance'
        PM: 'Program Management'
  - name: '800_53_j'
    description: 'NIST 800-53'
    document:
      source: 'http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r4.pdf'
      parsable: 'data/regimes/nist_800-53r4_appendix_j.tsv'
    etl:
      module: 'sckg.etl.nist_800_53_j'
      class: 'NIST80053J'
    meta:
      render_related: False
      families:
        AP: 'Authority and Purpose'
        AR: 'Accountability, Audit, and Risk Management'
        DI: 'Data Quality and Integrity'
        DM: 'Data Minimization and Retention'
        IP: 'Individual Participation and Redress'
        SE: 'Security'
        TR: 'Transparency'
        UL: 'Use Limitation'
  - name: '800_53r5'
    description: 'NIST 800-53r5'
    document:
      source: 'http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r5.pdf'
      parsable: 'data/regimes/nist_800-53r5.tsv'
    etl:
      module: 'sckg.etl.nist_800_53r5'
      class: 'NIST80053r5'
    meta:
      render_related: False
      families:
        AC: 'Access Control'
        AT: 'Awareness and Training'
        AU: 'Audit and Accountability'
        CA: 'Security Assessment and Authorization'
        CM: 'Configuration Management'
        CP: 'Contingency Planning'
        IA: 'Identification and Authentication'
        IR: 'Incident Response'
        MA: 'Maintenance'
        MP: 'Media Protection'
        PE: 'Physical and Environmental Protection'
        PL: 'Planning'
        PM: 'Program Management'
        PS: 'Personnel Security'
        PT: 'Personally Identifiable Information Processing and Transparency'
        RA: 'Risk Assessment'
        SA: 'System and Services Acquisition'
        SC: 'System and Communications Protection'
        SI: 'System and Information Integrity'
        SR: 'Supply Chain Risk Management'
  - name: '80053r5_to_csf'
    description: 'Mapping 800-53r5 to NIST CSF'
    document:
      source: 'https://csrc.nist.gov/CSRC/media/Publications/sp/800-53/rev-5/final/documents/csf-pf-to-sp800-53r5-mappings.xlsx'
      parsable: 'data/regimes/800_53r5_to_csf.tsv'
    etl:
      module: 'sckg.etl.80053r5CSF'
      class: 'R5CSF'
  - name: 'fedramp_high'
    description: 'FedRAMP High'
    document:
      source: 'https://www.fedramp.gov/assets/resources/documents/FedRAMP_Security_Controls_Baseline.xlsx'
      parsable: 'data/regimes/fedramp_high.tsv'
    baseline:
      regime_name: 'FedRAMP'
      baseline_name: 'High'
      control_regime: '800_53'
      uid_key: 'id'
  - name: 'fedramp_moderate'
    description: 'FedRAMP Moderate'
    document:
      source: 'https://www.fedramp.gov/assets/resources/documents/FedRAMP_Security_Controls_Baseline.xlsx'
      parsable: 'data/regimes/fedramp_moderate.tsv'
    baseline:
      regime_name: 'FedRAMP'
      baseline_name: 'Moderate'
      control_regime: '800_53'
      uid_key: 'id'
  - name: 'cnssi_1253_ci'
    description: 'CNSSI 1253 Classified Information Overlay'
    document:
      source: 'http://www.cnss.gov/CNSS/openDoc.cfm?DicUWFWDPKtdtDzjZgB/Tg=='
      parsable: 'data/regimes/cnssi_1253_classified_information.tsv'
    baseline:
      regime_name: 'CNSSI 1253'
      baseline_name: 'Classified Information'
      control_regime: '800_53'
      uid_key: 'control'
  - name: 'cnssi_1253_pii'
    description: 'CNSSI 1253 Privacy Overlay'
    document:
      source: 'http://www.cnss.gov/CNSS/openDoc.cfm?p+GaEPIY0/MkVrdBz4Wu3Q=='
      parsable: 'data/regimes/cnssi_1253_privacy.tsv'
    baseline:
      regime_name: 'CNSSI 1253'
      baseline_name: 'Privacy'
      control_regime: '800_53'
      uid_key: 'control'
  - name: 'dod_srg'
    description: 'DoD SRG'
    document:
      source: 'https://rmf.org/wp-content/uploads/2018/05/Cloud_Computing_SRG_v1r3.pdf'
      parsable: 'data/regimes/dod_srg.tsv'
    etl:
      module: 'sckg.etl.dod_srg'
      class: 'DoDSRG'
    baseline:
      regime_name: 'DoD SRG'
      baseline_name: 'None'
      control_regime: '800_53'
      uid_key: 'control'
  - name: 'cis'
    description: 'CIS CSC'
    document:
      source: 'https://learn.cisecurity.org/benchmarks'
      parsable: 'data/regimes/cis.tsv'
    etl:
      module: 'sckg.etl.cis'
      class: 'CIS'
  - name: 'pci_dss'
    description: 'PCI DSS'
    document:
      source: 'https://www.pcisecuritystandards.org/document_library'
      parsable: 'data/regimes/pcidss_v321.tsv'
    etl:
      module: 'sckg.etl.pci_dss'
      class: 'PCIDSS'
  - name: 'nist_csf'
    description: 'NIST CSF'
    document:
      source: 'https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.04162018.pdf'
      parsable: 'data/regimes/nist_csf.tsv'
    etl:
      module: 'sckg.etl.nist_csf'
      class: 'NISTCSF'
  - name: 'cac_rules'
    description: 'ComplianceAsCode Rules'
    document:
      source: 'https://github.com/ComplianceAsCode/content'
      # parsable can be a file or dir
      parsable: 'data/compliance_as_code/linux_os/guide'
    etl:
      module: 'sckg.etl.cac.rules'
      class: 'Rules'
  - name: 'cac_bash_rhel7_stig'
    description: 'rhel7-script-stig.sh'
    document:
      source: 'https://github.com/ComplianceAsCode/content'
      parsable: 'data/compliance_as_code/build/bash/rhel7-script-stig.sh'
    etl:
      module: 'sckg.etl.cac.bash'
      class: 'Bash'
  - name: 'cac_bash_rhel7_pcidss'
    description: 'rhel7-script-pci-dss.sh'
    document:
      source: 'https://github.com/ComplianceAsCode/content'
      parsable: 'data/compliance_as_code/build/bash/rhel7-script-pci-dss.sh'
    etl:
      module: 'sckg.etl.cac.bash'
      class: 'Bash'
  - name: 'cac_bash_rhel7_cis'
    description: 'rhel7-script-cis.sh'
    document:
      source: 'https://github.com/ComplianceAsCode/content'
      parsable: 'data/compliance_as_code/build/bash/rhel7-script-cis.sh'
    etl:
      module: 'sckg.etl.cac.bash'
      class: 'Bash'
  - name: 'cac_bash_fedora_pcidss'
    description: 'fedora-script-pci-dss.sh'
    document:
      source: 'https://github.com/ComplianceAsCode/content'
      parsable: 'data/compliance_as_code/build/bash/fedora-script-pci-dss.sh'
    etl:
      module: 'sckg.etl.cac.bash'
      class: 'Bash'
  - name: 'cac_bash_debian9'
    description: 'debian9-script-standard.sh'
    document:
      source: 'https://github.com/ComplianceAsCode/content'
      parsable: 'data/compliance_as_code/build/bash/debian9-script-standard.sh'
    etl:
      module: 'sckg.etl.cac.bash'
      class: 'Bash'
  - name: 'cac_bash_ubuntu1804'
    description: 'ubuntu1804-script-standard.sh'
    document:
      source: 'https://github.com/ComplianceAsCode/content'
      parsable: 'data/compliance_as_code/build/bash/ubuntu1804-script-standard.sh'
    etl:
      module: 'sckg.etl.cac.bash'
      class: 'Bash'
  - name: 'dod_cci'
    description: 'DoD CCI'
    document:
      source: 'https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/u_cci_list.zip'
      parsable: 'data/regimes/U_CCI_List.xml'
    etl:
      module: 'sckg.etl.dod_cci'
      class: 'DoDCCI'
    meta:
      updated: '02 Feb 2017'
  - name: 'gpospp'
    description: 'NIAP GPOS'
    document:
      source: 'https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_General_Purpose_Operating_System_V1R6_SRG.zip'
      parsable: 'data/regimes/U_General_Purpose_Operating_System_SRG_V1R6_Manual-xccdf.xml'
    etl:
      module: 'sckg.etl.stig'
      class: 'STIG'
    baseline:
      regime_name: 'STIG'
      baseline_name: 'NIAP GPOS'
      control_regime: 'DoD CCI'
      control_baseline: '02 Feb 2017'
      uid_key: 'name'
  - name: 'rhel7_stig'
    description: 'RHEL7 STIG'
    document:
      source: 'https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_Red_Hat_Enterprise_Linux_7_V2R5_STIG.zip'
      parsable: 'data/regimes/U_Red_Hat_Enterprise_Linux_7_STIG_V2R5_Manual-xccdf.xml'
    etl:
      module: 'sckg.etl.stig'
      class: 'STIG'
    baseline:
      regime_name: 'STIG'
      baseline_name: 'RHEL7 STIG'
      control_regime: 'DoD CCI'
      control_baseline: '02 Feb 2017'
      uid_key: 'name'
  - name: 'ubuntu1604_stig'
    description: 'Ubuntu1604 STIG'
    document:
      source: 'https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_Canonical_Ubuntu_16-04_LTS_V1R2_STIG.zip'
      parsable: 'data/regimes/U_Canonical_Ubuntu_16-04_LTS_STIG_V1R2_Manual-xccdf.xml'
    etl:
      module: 'sckg.etl.stig'
      class: 'STIG'
    baseline:
      regime_name: 'STIG'
      baseline_name: 'Ubuntu1604 STIG'
      control_regime: 'DoD CCI'
      control_baseline: '02 Feb 2017'
      uid_key: 'name'
  - name: 'tic'
    description: 'Trusted Internet Connection 3'
    document:
      source: 'https://www.cisa.gov/sites/default/files/publications/CISA_TIC%203.0%20Vol.%203%20Security%20Capabilities%20Catalog.pdf'
      parsable: 'data/regimes/tic3.tsv'
    etl:
      module: 'sckg.etl.tic3'
      class: 'TIC3'
    baseline:
      regime_name: 'TIC'
      baseline_name: 'NIST CSF'
      control_regime: 'NIST CSF'
      control_baseline: 'TIC 3'
    meta:
      csf_abbreviations:
        RS.AN: "Analysis (RS.AN): Analysis is conducted to ensure effective response and support recovery activities."
        DE.AE: "Anomalies and Events (DE.AE): Anomalous activity is detected and the potential impact of events is understood."
        ID.AM: "Asset Management (ID.AM): The data, personnel, devices, systems, and facilities that enable the organization to achieve business purposes are identified and managed consistent with their relative importance to organizational objectives and the organization’s risk strategy."
        PR.AT: "Awareness and Training (PR.AT): The organization’s personnel and partners are provided cybersecurity awareness education and are trained to perform their cybersecurity-related duties and responsibilities consistent with related policies, procedures, and agreements."
        ID.BE: "Business Environment (ID.BE): The organization’s mission, objectives, stakeholders, and activities are understood and prioritized; this information is used to inform cybersecurity roles, responsibilities, and risk management decisions."
        RC.CO: "Communications (RC.CO): Restoration activities are coordinated with internal and external parties (e.g.  coordinating centers, Internet Service Providers, owners of attacking systems, victims, other CSIRTs, and vendors)."
        RS.CO: "Communications (RS.CO): Response activities are coordinated with internal and external stakeholders (e.g. external support from law enforcement agencies)."
        PR.DS: "Data Security (PR.DS): Information and records (data) are managed consistent with the organization’s risk strategy to protect the confidentiality, integrity, and availability of information."
        DE.DP: "Detection Processes (DE.DP): Detection processes and procedures are maintained and tested to ensure awareness of anomalous events."
        ID.GV: "Governance (ID.GV): The policies, procedures, and processes to manage and monitor the organization’s regulatory, legal, risk, environmental, and operational requirements are understood and inform the management of cybersecurity risk."
        PR.AC: "Identity Management, Authentication and Access Control (PR.AC): Access to physical and logical assets and associated facilities is limited to authorized users, processes, and devices, and is managed consistent with the assessed risk of unauthorized access to authorized activities and transactions."
        RC.IM: "Improvements (RC.IM): Recovery planning and processes are improved by incorporating lessons learned into future activities."
        RS.IM: "Improvements (RS.IM): Organizational response activities are improved by incorporating lessons learned from current and previous detection/response activities."
        PR.IP: "Information Protection Processes and Procedures (PR.IP): Security policies (that address purpose, scope, roles, responsibilities, management commitment, and coordination among organizational entities), processes, and procedures are maintained and used to manage protection of information systems and assets."
        PR.MA: "Maintenance (PR.MA): Maintenance and repairs of industrial control and information system components are performed consistent with policies and procedures."
        RS.MI: "Mitigation (RS.MI): Activities are performed to prevent expansion of an event, mitigate its effects, and resolve the incident."
        PR.PT: "Protective Technology (PR.PT): Technical security solutions are managed to ensure the security and resilience of systems and assets, consistent with related policies, procedures, and agreements."
        RC.RP: "Recovery Planning (RC.RP): Recovery processes and procedures are executed and maintained to ensure restoration of systems or assets affected by cybersecurity incidents."
        RS.RP: "Response Planning (RS.RP): Response processes and procedures are executed and maintained, to ensure response to detected cybersecurity incidents."
        ID.RA: "Risk Assessment (ID.RA): The organization understands the cybersecurity risk to organizational operations (including mission, functions, image, or reputation), organizational assets, and individuals."
        ID.RM: "Risk Management Strategy (ID.RM): The organization’s priorities, constraints, risk tolerances, and assumptions are established and used to support operational risk decisions."
        DE.CM: "Security Continuous Monitoring (DE.CM): The information system and assets are monitored to identify cybersecurity events and verify the effectiveness of protective measures."
        ID.SC: "Supply Chain Risk Management (ID.SC): The organization’s priorities, constraints, risk tolerances, and assumptions are established and used to support risk decisions associated with managing supply chain risk. The organization has established and implemented the processes to identify, assess and manage supply chain risks."

